server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 230406
    keyStoreType: PKCS12
    keyAlias: myapp

  port: 4245

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/url
      database: url
      auto-index-creation: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
