
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/url
      database: url
      auto-index-creation: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none
server:
  port: 4245